### ISSUE TITLE
unable to import module from 2.0.0 onwards

### ISSUE THREAD

**Issue by T3le** [cityssm/mssql-multi-pool#480]
Hi, thank you for your multi pool implementation, it would be very convienient if I get it working. Unfortunately I get an import error
 within our low code environment when trying to import the latest module. V1.5.0 is the last version that does import correctly. 

The error is; TypeError: Invalid host defined options  at eval (eval at testESMImport...

So it seems to be something with the ESM options of the project. I could't find an online validator to pinpoint the issue, but maybe you have any idea? 

https://github.com/cityssm/mssql-multi-pool/compare/v1.5.0...v2.0.0

**Comment by dangowans** [comment]
Thanks for reaching out @T3le .

I did a [quick Google for "TypeError: Invalid host defined options"](https://www.google.com/search?q=+TypeError%3A+Invalid+host+defined+options).

Does your low code environment accept ES modules? If not, that's likely the problem, or possibly one of the tools used in your project doesn't support ES modules.

If that's the case, unfortunately we don't have the resources here to maintain both CommonJS and ES Module packages.

**Comment by T3le** [comment]
Hi, thank you for your response. It does accept other ES modules, that's why I got a bit confused by the error message. Since it is a small bit of code anyway i took the liberty to implement your functions in my project instead. Thanks again and have a nice day!

**Comment by dangowans** [comment]
Glad to hear you found a solution that works for you and your project, 👍
